In [3]:
import numpy as np

In [10]:
Q1) 
X = np.array([
    [100, 80, 50,  0],   # TV
    [20,  25, 30, 35],   # Search
    [10,  10, 15, 20]    # Social
])

X.T

SyntaxError: unmatched ')' (1883192688.py, line 1)

In [ ]:
Q2) 
np.stack([X_UK, X_US, X_FR, X_DE, X_CA], axis = 0)

In [12]:
# Q3) 
X = np.random.rand(5, 104, 3) 

(X - X.mean())/X.std()

array([[[ 0.74177607,  0.32878029,  0.95311923],
        [ 0.74161222, -0.23471138, -0.51199785],
        [ 0.77551749,  0.60721062, -1.04474603],
        ...,
        [-0.91585633,  0.99730189,  1.14310577],
        [ 0.01418788,  0.35770672,  0.50207848],
        [-0.36707619,  0.45434104, -0.40507819]],

       [[ 1.15237499, -1.43643161,  1.67765021],
        [-1.3088646 , -1.40579119, -0.99730415],
        [-0.27079805,  1.28677294, -0.71544001],
        ...,
        [ 1.28084337,  0.6319702 ,  1.61546299],
        [ 1.14539366, -1.24986614, -0.37535876],
        [-0.01278318,  0.21927521,  1.18045426]],

       [[-1.01925033, -0.4552585 , -0.8729852 ],
        [ 0.17425212, -1.31397419,  0.24211564],
        [-1.2503908 ,  0.36605458,  1.25937662],
        ...,
        [ 1.7263254 , -0.82203256,  0.024666  ],
        [ 0.19858641, -0.80743099, -0.31500199],
        [-1.45029825,  1.07706266,  0.55068444]],

       [[ 1.27313812,  0.12321918,  0.04181056],
        [-0.22743982,  0

In [13]:
beta = np.random.normal(0.05, 0.01, size=(4, 2000, 5, 3))  
# shape: (chains, draws, markets, channels)

X = np.random.rand(5, 104, 3)
# shape: (markets, weeks, channels)



ValueError: operands could not be broadcast together with shapes (4,2000,5,3) (5,104,3) 

In [14]:
beta = np.array([0.3, 0.2, 0.1]) 

X = np.array([
    [100, 200, 300], 
    [400, 500, 600]
])



array([[ 30.,  40.,  30.],
       [120., 100.,  60.]])

In [22]:
beta = np.array([[0.3], [0.2], [0.1]])     # shape (3,1)
X = np.array([
    [100, 200, 300],
    [400, 500, 600]
])  # shape (2,3)

beta.T @ X.T

array([[100., 280.]])

In [23]:
beta.T

array([[0.3, 0.2, 0.1]])

In [24]:
X.T

array([[100, 400],
       [200, 500],
       [300, 600]])

In [26]:
X = np.random.rand(2, 52, 3)
X.sum(axis = 2)

(2, 52)

In [38]:
t_1 = np.arange(52)
t_2 = np.arange(52)

np.stack([t_1, t_2], axis = 0)

(2, 52)

In [43]:
media = np.random.rand(100, 3)     # (time, channels)
controls = np.random.rand(100, 2)  # (time, controls)

np.hstack([media, controls]).shape

(100, 5)

In [44]:
spend = np.array([1000, 2000, 3000, 4000])

(spend - np.mean(spend)) / np.std(spend)

array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079])

In [46]:
spend = np.array([0, 50, 100, 200])
alpha = 1.5
theta = 80
(spend ** alpha) / ((theta ** alpha) + (spend**alpha))

array([0.        , 0.33070339, 0.58290624, 0.79809593])

In [ ]:
beta[:, :, None, :]  * spend_media[None, None, :, :]

In [48]:
markets = 4
products = 3
time = 100
channels = 5

X = np.random.rand(markets, products, time, channels)

In [54]:
beta = np.random.rand(markets, channels)
contri = beta[:, None, None, :] * X
contri.shape



(4, 3, 100, 5)

In [57]:
X.shape

(4, 3, 100, 5)

In [59]:
beta.T.shape

(5, 4)

In [56]:
(X @ beta.T).shape

(4, 3, 100, 4)

In [61]:
np.einsum("mptc, mc -> mpt", X, beta).shape

(4, 3, 100)

In [62]:
mu = np.sum(X * beta[:, None, None, :], axis=-1)
mu.shape

(4, 3, 100)

In [65]:
X = np.random.rand(markets, products, time, channels)
np.reshape(X, (markets * products * time, channels)).shape

(1200, 5)

In [83]:
beta_post = np.random.rand(2, 500, markets, products, channels)
# beta_post = np.reshape(beta_post, (2*500, markets, products, channels))

contrib = beta_post[:, :, :, :, None, :] * X[None, None, :, :, :, :]

contrib.sum(-1)

(2, 500, 4, 3, 100)

In [78]:
beta_post.shape

(2, 500, 4, 3, 5)

In [77]:
X.shape

(4, 3, 100, 5)

In [90]:
trend = np.arange(52) 
trend[None, None, :] * np.ones((2,3))[:, :, None]

array([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
         24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
         36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47.,
         48., 49., 50., 51.]],

       [[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
         12

In [91]:
controls = np.random.rand(markets, products, time, 2)
controls.shape

(4, 3, 100, 2)

In [92]:
X.shape

(4, 3, 100, 5)

In [95]:
np.concatenate([controls, X], axis = -1).shape

(4, 3, 100, 7)

In [99]:
(X - np.mean(X)) / np.std(X)

ValueError: operands could not be broadcast together with shapes (4,3,100,5) (0,) 

In [101]:
contrib = np.random.rand(4,3,100,5)

np.reshape(contrib, (4*3*100, 5))

(1200, 5)

In [106]:
X.shape

(4, 3, 100, 5)

In [108]:
X[2, 0, :, (1,3)].T.shape

(100, 2)

In [119]:
t_1 = np.arange(52)
np.tile(np.arange(52), (3, 1)).T.shape
# np.stack([t_1, t_2, t_3], axis = 1).shape

(52, 3)

In [127]:
y = np.random.rand(156)
y[52:103]

array([0.14011153, 0.77155341, 0.96281446, 0.43927759, 0.87823506,
       0.96268779, 0.36725454, 0.27723981, 0.35871068, 0.31488914,
       0.46217127, 0.08675807, 0.31421812, 0.80989976, 0.02489861,
       0.02634507, 0.31964321, 0.88119565, 0.03257173, 0.6009734 ,
       0.13393149, 0.69761116, 0.27591827, 0.10413084, 0.7087377 ,
       0.97806316, 0.8616205 , 0.8427721 , 0.56671674, 0.70023205,
       0.05996245, 0.23572821, 0.19462265, 0.09549433, 0.3736133 ,
       0.13386654, 0.2293001 , 0.26844793, 0.93741942, 0.47314709,
       0.57330878, 0.70579613, 0.06992926, 0.88788666, 0.18529963,
       0.20475767, 0.09316972, 0.55882051, 0.84490436, 0.61446789,
       0.45883503])